# Generated by Django 4.1 on 2022-09-06 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEPARTAMENTO',
            fields=[
                ('DEP_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id departamento')),
                ('DEP_NOMBRE', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de departamento')),
                ('DEP_DESCRIPCION', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de departamento')),
                ('DEP_CANTIDADHABITACIONES', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de habitaciones')),
                ('DEP_CANTIDADCAMAS', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de camas')),
                ('DEP_CANTIDADBANOS', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de baños')),
                ('DEP_CANTIDADPERSONAS', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de personas')),
                ('DEP_DIRECCION', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion departamento')),
                ('DEP_VALOR_DIA', models.IntegerField(blank=True, null=True, verbose_name='Valor arriendo por dia')),
                ('DEP_IMAGEN1', models.ImageField(null=True, upload_to='departamentos')),
                ('DEP_IMAGEN2', models.ImageField(null=True, upload_to='departamentos')),
                ('DEP_IMAGEN3', models.ImageField(null=True, upload_to='departamentos')),
            ],
            options={
                'db_table': 'DEPARTAMENTO',
            },
        ),
        migrations.CreateModel(
            name='ESTADO',
            fields=[
                ('EST_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id estado')),
                ('EST_NOMBRE', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de estado')),
            ],
            options={
                'db_table': 'ESTADO',
            },
        ),
        migrations.CreateModel(
            name='TRANSPORTE',
            fields=[
                ('TRA_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id transporte')),
                ('TRA_NOMBRESERVICIO', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre servicio de transporte')),
                ('TRA_HORARIO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Horario del transporte')),
                ('TRA_VEHICULO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vehiculo de transporte')),
                ('TRA_CONDUCTOR', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre conductor')),
                ('TRA_VALOR', models.IntegerField(blank=True, null=True, verbose_name='Valor del transporte')),
            ],
            options={
                'db_table': 'TRANSPORTE',
            },
        ),
        migrations.CreateModel(
            name='ZONA',
            fields=[
                ('ZON_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id zona')),
                ('ZON_NOMBRE', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre zona')),
            ],
            options={
                'db_table': 'ZONA',
            },
        ),
        migrations.CreateModel(
            name='TOUR',
            fields=[
                ('TOU_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id servicio de tour')),
                ('TOU_NOMBRE', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de tour')),
                ('TOU_DESCRIPCION', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del tour')),
                ('TOU_VALOR', models.IntegerField(blank=True, null=True, verbose_name='Valor del tour')),
                ('ZON_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.zona', verbose_name='Zona')),
            ],
            options={
                'db_table': 'TOUR',
            },
        ),
        migrations.CreateModel(
            name='INVENTARIO_DEPARTAMENTO',
            fields=[
                ('INV_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id inventario')),
                ('INV_CANTIDADTAZAS', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de tazas')),
                ('INV_CANTIDADVASOS', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de tazas')),
                ('INV_CANTIDADCUCHARAS', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de tazas')),
                ('INV_CANTIDADCUCHILLOS', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de tazas')),
                ('INV_CANTIDADTENEDORES', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de tazas')),
                ('INV_CANTIDADSILLAS', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de tazas')),
                ('INV_CANTIDADTOALLAS', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de tazas')),
                ('DEP_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.departamento', verbose_name='Departamento')),
            ],
            options={
                'db_table': 'INVENTARIO_DEPARTAMENTO',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='EST_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='TOU_ID1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tour_asociado_1', to='home.tour', verbose_name='Tour asociado'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='TOU_ID2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tour_asociado_2', to='home.tour', verbose_name='Tour 2 asociado'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='TOU_ID3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tour_asociado_3', to='home.tour', verbose_name='Tour 3 asociado'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='ZON_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.zona', verbose_name='Zona'),
        ),
    ]
