# Generated by Django 4.1 on 2022-09-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_inventario_departamento_inv_cantidadcucharas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='INVENTARIO',
            fields=[
                ('INV_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='Id inventario')),
                ('INV_MICROONDAS', models.BooleanField(default=False, verbose_name='Microondas')),
                ('INV_HORNOELECTRICO', models.BooleanField(default=False, verbose_name='Horno Electrico')),
                ('INV_DEPARTAMENTO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.departamento')),
            ],
            options={
                'db_table': 'INVENTARIO',
            },
        ),
    ]
