# Generated by Django 4.1 on 2022-09-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_probar_onetoone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probar_onetoone',
            name='PRO_DEP',
        ),
        migrations.RemoveField(
            model_name='probar_onetoone',
            name='PRO_TEXTO',
        ),
    ]
