# Generated by Django 4.1 on 2022-09-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_probar_onetoone_pro_dep_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PROBAR_ONETOONE',
        ),
    ]
