# Generated by Django 4.1 on 2022-09-27 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_delete_probar_onetoone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESERVA',
            fields=[
                ('RES_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Reserva')),
                ('RES_FECHA_INICIO', models.DateField(blank=True, null=True)),
                ('RES_FECHA_TERMINO', models.DateField(blank=True, null=True)),
                ('RES_CANTIDAD_DIAS', models.IntegerField(blank=True, null=True)),
                ('RES_REGISTRO_ASISTENTES', models.TextField(blank=True, help_text='Ingrese nombre y rut de los asistentes a la reserva', null=True)),
                ('RES_DESEA_TOUR', models.BooleanField(blank=True, default=False, null=True, verbose_name='Desea tour')),
                ('RES_TOUR_1', models.IntegerField(blank=True, null=True)),
                ('RES_TOUR_2', models.IntegerField(blank=True, null=True)),
                ('RES_TOUR_3', models.IntegerField(blank=True, null=True)),
                ('RES_DESEA_TRANSPORTE', models.BooleanField(blank=True, default=False, null=True, verbose_name='Desea transporte')),
                ('RES_TRANSPORTE_1', models.IntegerField(blank=True, null=True)),
                ('RES_TRANSPORTE_2', models.IntegerField(blank=True, null=True)),
                ('RES_VALOR_RESERVA', models.IntegerField(blank=True, null=True)),
                ('RES_DEPARTAMENTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departamento')),
                ('RES_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
