# Generated by Django 4.1 on 2022-09-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RESERVA',
        ),
    ]
