# Generated by Django 4.1 on 2022-09-27 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_delete_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESERVA',
            fields=[
                ('RES_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Reserva')),
                ('RES_FECHA_INICIO', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('RES_FECHA_TERMINO', models.DateField(blank=True, null=True, verbose_name='Fecha termino')),
                ('RES_CANTIDAD_DIAS', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de dias')),
                ('RES_ASISTENTES', models.TextField(blank=True, help_text='Ingrese nombre y rut de los asistentes a la reserva', null=True, verbose_name='Asistentes')),
                ('RES_DESEA_TOUR', models.BooleanField(blank=True, default=False, null=True, verbose_name='Desea tour')),
                ('RES_TOUR_1', models.IntegerField(blank=True, null=True, verbose_name='Tour 1')),
                ('RES_TOUR_2', models.IntegerField(blank=True, null=True, verbose_name='Tour 2')),
                ('RES_TOUR_3', models.IntegerField(blank=True, null=True, verbose_name='Tour 3')),
                ('RES_DESEA_TRANSPORTE', models.BooleanField(blank=True, default=False, null=True, verbose_name='Desea transporte')),
                ('RES_TRANSPORTE_1', models.IntegerField(blank=True, null=True, verbose_name='Transporte ida')),
                ('RES_TRANSPORTE_2', models.IntegerField(blank=True, null=True, verbose_name='Transporte vuelta')),
                ('RES_VALOR_RESERVA', models.IntegerField(blank=True, null=True, verbose_name='Valor de la reserva')),
                ('RES_DEPARTAMENTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departamento')),
                ('RES_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RESERVA',
            },
        ),
    ]
