# Generated by Django 4.1 on 2022-09-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RESERVA',
        ),
    ]
