# Generated by Django 4.1 on 2022-10-15 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_reserva_res_valor_final_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='DEP_CHECK_LIST_FECHA',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
