# Generated by Django 4.1 on 2022-10-15 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_departamento_dep_check_list_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='DEP_CHECK_LIST_FECHA',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
