# Generated by Django 4.1 on 2022-10-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_departamento_dep_check_list_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='DEP_CHECK_LIST_FECHA',
        ),
    ]
