# Generated by Django 4.1 on 2022-10-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_departamento_dep_check_list_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='DEP_CHECK_LIST_FECHA',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
