# Generated by Django 4.1 on 2022-10-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_departamento_dep_check_list_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='RES_VALOR_FINAL_RESERVA',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='RES_VALOR_TOTAL',
        ),
    ]
