# Generated by Django 4.1 on 2022-10-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_reserva_res_valor_final_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='RES_DEPOSITO_GARANTIA',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Deposito de garantía'),
        ),
    ]
