# Generated by Django 4.1 on 2022-10-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_reserva_res_deposito_garantia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAGO',
            fields=[
                ('PAG_ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pago')),
                ('PAG_CANTIDAD_PAGADA', models.IntegerField(blank=True, null=True, verbose_name='Cantidad pagada')),
                ('PAG_FECHA_INGRESO', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PAGO',
            },
        ),
    ]
