# Generated by Django 4.1 on 2022-10-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='PAG_METODO_PAGO',
            field=models.IntegerField(blank=True, choices=[(1, 'Débito'), (2, 'Crédito'), (3, 'Transferencia'), (4, 'Efectivo')], default=1, null=True),
        ),
    ]
