# Generated by Django 4.1 on 2022-10-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_pago_pag_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='PAG_METODO_PAGO',
            field=models.CharField(blank=True, choices=[('DEBÍTO', 'Débito'), ('CRÉDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo')], max_length=100, null=True),
        ),
    ]
