# Generated by Django 4.1 on 2022-11-02 16:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_pago_pag_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='TOU_DESCRIPCION',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
