# Generated by Django 4.1 on 2022-11-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_tour_tou_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INVENTARIO',
        ),
    ]
